spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  thymeleaf:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api
jwt:
  secret-key: "${JWT_SECRET_KEY}"
cloud:
  aws:
    s3:
      bucket: "${AWS_S3_BUCKET}"
    credentials:
      access-key: "${AWS_S3_ACCESS_KEY}"
      secret-key: "${AWS_S3_SECRET_KEY}"
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:2345/kio-school-database
    username: myuser
    password: mypassword
jwt:
  secret-key: 512393ea8dee67633d7f1197c4938239f57c1a323a227e919977f0b478c5f5fd3a4dab07ba1a796297c5cd7c9519e6403ad2742e0c07024290aafa3d6f9f2424